### ISSUE TITLE
can you quickly retest your glive.sh ?

### ISSUE THREAD

**Issue by donwade** [yilonglucky/rp5_tc358743#1]
I manually enter 
+ USERNAME=dwade
+ export DISPLAY=:0
+ DISPLAY=:0
+ export XAUTHORITY=/home/dwade/.Xauthority
+ XAUTHORITY=/home/dwade/.Xauthority
+ export LD_LIBRARY_PATH=:/home/dwade/aarch64.boost-Release/lib:/home/dwade/aarch64/lib:/usr/local/lib:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/gstreamer-1.0
+ LD_LIBRARY_PATH=:/home/dwade/aarch64.boost-Release/lib:/home/dwade/aarch64/lib:/usr/local/lib:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/gstreamer-1.0
+ set -ex
+ gst-launch-1.0 -v v4l2src device=/dev/video0 num-buffers=300 '!' video/x-raw,format=YUV,width=1920,height=1080 '!' videoconvert '!' xvimagesink 'render-rectangle=<450,-250,1020,1480>' sync=false

but it responds with.

**WARNING: erroneous pipeline: could not link v4l2src0 to videoconvert0, neither element can handle caps video/x-raw, format=(string)YUV, width=(int)1920, height=(int)1080**

1. Are you a raspi -5?
2. What OS version are you using ?

uname -a
Linux dwade-15R **6.8.0-45-generic** #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yilonglucky** [comment]
Hi，
My uname info:
Linux a 6.6.37-v8-16k+ #14 SMP PREEMPT Tue Sep 10 14:59:35 CST 2024 aarch64 GNU/Linux

It seems your v4l2 node can't support YUV yet.
Here are cmd maybe you need:
v4l2-ctl --list-devices
v4l2-ctl  --all
v4l2-ctl --device=/dev/video0 --list-formats-ext

MEDIANODE=/dev/media3
media-ctl -d $MEDIANODE -p

**Comment by donwade** [comment]
You are correct! thanks for your guidance.
